### PR TITLE
Update ring-ping

### PR DESCRIPTION
**Pull request by jan-vandenberg**
Fix typo.

### CODE REVIEW

**Review by wschoot — APPROVED** [review]
LGTM

**Comment by ytti** [comment]
Please educate me, why is this a typo? My naive understanding; 'lot of modification' implies single modification of multiple changes, 'lot of modifications' implies multiple modifications of unspecified amount of changes per modification'.

**Comment by ytti** [comment]
Thanks, I was just looking at the singular and plural and wondering why singular is typo, just for my edification, singular would have been ok?

**Comment by grizz** [comment]
You made me curious, since singular still seemed like a typo to me. I believe it is, it should refer to a plural:

https://english.stackexchange.com/questions/186113/shouldn-t-we-use-lots-of-with-plural-nouns-and-a-lot-of-with-singular-ones#:~:text=A%20lot%20of%20things%20means,the%20plural%20form%20of%20lot.

**Comment by arjenz** [comment]
That stackexchange post discusses if/when the plural "lots" should be used, don't think that applies here.
I agree with ytti, "a lot of modifications" and "a lot of modification" are both correct but with different meanings (I haven't looked at history so I don't know which meaning applies here).

**Pull request merged**
